// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ePVMQiT9lh34GWNxi6vMx8-FD_k_McQ',
    appId: '1:906803307520:web:df604a89bdbedc4bf9e4e5',
    messagingSenderId: '906803307520',
    projectId: 'pennywise-980f9',
    authDomain: 'pennywise-980f9.firebaseapp.com',
    storageBucket: 'pennywise-980f9.firebasestorage.app',
    measurementId: 'G-746W5C2MKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwGbbllyCfyy4uDIOmPbBmnuvbKNf_sVs',
    appId: '1:906803307520:android:3b5ead30140e9c10f9e4e5',
    messagingSenderId: '906803307520',
    projectId: 'pennywise-980f9',
    storageBucket: 'pennywise-980f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQV3hTnvz1hYtPlb3j1Qucxigs_tQPsXM',
    appId: '1:906803307520:ios:61bce2e7562befc4f9e4e5',
    messagingSenderId: '906803307520',
    projectId: 'pennywise-980f9',
    storageBucket: 'pennywise-980f9.firebasestorage.app',
    iosBundleId: 'com.example.pennyWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQV3hTnvz1hYtPlb3j1Qucxigs_tQPsXM',
    appId: '1:906803307520:ios:61bce2e7562befc4f9e4e5',
    messagingSenderId: '906803307520',
    projectId: 'pennywise-980f9',
    storageBucket: 'pennywise-980f9.firebasestorage.app',
    iosBundleId: 'com.example.pennyWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ePVMQiT9lh34GWNxi6vMx8-FD_k_McQ',
    appId: '1:906803307520:web:f9764a1b457d181ff9e4e5',
    messagingSenderId: '906803307520',
    projectId: 'pennywise-980f9',
    authDomain: 'pennywise-980f9.firebaseapp.com',
    storageBucket: 'pennywise-980f9.firebasestorage.app',
    measurementId: 'G-29KXZX1SY7',
  );
}
